STWFInstallDefaultEquipment={
//"Exported from Arsenal by Cpt Horny";

//"Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

//"Add containers";
player forceAddUniform "ffaa_brilat_CombatUniform_item_b";
player addItemToUniform "ffaa_nvgoggles";
for "_i" from 1 to 4 do {player addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
player addItemToUniform "ACE_microDAGR";
player addItemToUniform "ACE_EarPlugs";
player addItemToUniform "ACE_MapTools";
player addItemToUniform "Chemlight_green";
player addItemToUniform "CUP_30Rnd_556x45_Stanag";
player addVest "ffaa_brilat_chaleco_02_bs";
for "_i" from 1 to 2 do {player addItemToVest "ffaa_granada_alhambra";};
player addItemToVest "SmokeShell";
player addItemToVest "SmokeShellGreen";
player addItemToVest "SmokeShellBlue";
player addItemToVest "SmokeShellOrange";
player addItemToVest "Chemlight_green";
for "_i" from 1 to 2 do {player addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 3 do {player addItemToVest "ffaa_9x19_pistola";};
player addBackpack "ffaa_brilat_mochila_boscoso_municion";
for "_i" from 1 to 10 do {player addItemToBackpack "SmokeShell";};
for "_i" from 1 to 10 do {player addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 2 do {player addItemToBackpack "CUP_SMAW_HEAA_M";};
player addHeadgear "ffaa_brilat_casco_b";
player addGoggles "G_Lowprofile";

//"Add weapons";
player addWeapon "CUP_arifle_M4A1_BUIS_camo_GL";
player addPrimaryWeaponItem "CUP_muzzle_snds_M16_camo";
player addPrimaryWeaponItem "ACE_acc_pointer_green";
player addPrimaryWeaponItem "ACE_optic_MRCO_2D";
player addWeapon "CUP_launch_Mk153Mod0";
player addSecondaryWeaponItem "CUP_optic_SMAW_Scope";
player addWeapon "ffaa_armas_p226";
player addWeapon "ACE_Vector";

//"Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "ItemRadio";
player linkItem "ACE_NVG_Gen2";

};

STWFInstallDefaultDayEquipment={
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  
 player addHeadgear 'rhsusf_lwh_helmet_marpatwd_headset_blk2';
 player addGoggles 'rhs_ess_black';
 player addUniform 'rhs_uniform_FROG01_wd';
 player addVest 'rhsusf_mbav_light';
 player addBackPack 'rhsusf_falconii_mc';
 player addmagazine 'rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red';
 player addweapon 'rhs_weap_m4a1_carryhandle';
 player addmagazine 'rhsusf_mag_17Rnd_9x19_JHP';
 player addweapon 'rhsusf_weap_glock17g4';
 player addmagazine '<null>';
 player addweapon 'Rangefinder';
 player addPrimaryWeaponItem 'rhsusf_acc_SFMB556';
 player addPrimaryWeaponItem 'rhsusf_acc_ACOG3_USMC';
 player addPrimaryWeaponItem 'bipod_03_F_blk';
 player addHandgunItem 'rhsusf_acc_omega9k';
 player addHandgunItem 'acc_flashlight_pistol';
 player addItemToUniform 'FirstAidKit';
 player addItemToUniform 'FirstAidKit';
 player addItemToUniform 'rhsusf_mag_17Rnd_9x19_FMJ';
 player addItemToUniform 'rhsusf_mag_17Rnd_9x19_FMJ';
 player addItemToVest 'HandGrenade';
 player addItemToVest 'HandGrenade';
 player addItemToVest 'HandGrenade';
 player addItemToVest 'HandGrenade';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'Chemlight_green';
 player addItemToVest 'rhs_mag_an_m8hc';
 player linkItem 'ItemMap';
 player linkItem 'ItemCompass';
 player linkItem 'ItemWatch';
 player linkItem 'ItemRadio';
 player linkItem 'ItemGPS';
 player linkItem 'Rangefinder';

};

STWFInstallDefaultNightEquipment={
  //"Remove existing items";
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;

  player addHeadgear 'rhsusf_opscore_bk_pelt';
  player addGoggles 'G_Lowprofile';
  player addUniform 'rhs_uniform_g3_blk';
  player addVest 'V_TacVestIR_blk';
  player addBackPack 'B_AssaultPack_blk';
  player addmagazine 'rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red';
  player addweapon 'rhs_weap_m4a1_carryhandle';
  player addmagazine 'rhsusf_mag_17Rnd_9x19_JHP';
  player addweapon 'rhsusf_weap_glock17g4';
  player addmagazine '<null>';
  player addweapon 'Rangefinder';
  player addPrimaryWeaponItem 'rhsusf_acc_nt4_black';
  player addPrimaryWeaponItem 'acc_pointer_IR';
  player addPrimaryWeaponItem 'optic_Nightstalker';
  player addPrimaryWeaponItem 'bipod_03_F_blk';
  player addHandgunItem 'rhsusf_acc_omega9k';
  player addHandgunItem 'acc_flashlight_pistol';
  player addItemToUniform 'FirstAidKit';
  player addItemToUniform 'FirstAidKit';
  player addItemToUniform 'rhsusf_mag_17Rnd_9x19_FMJ';
  player addItemToUniform 'rhsusf_mag_17Rnd_9x19_FMJ';
  player addItemToVest 'HandGrenade';
  player addItemToVest 'HandGrenade';
  player addItemToVest 'HandGrenade';
  player addItemToVest 'HandGrenade';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'Chemlight_green';
  player addItemToVest 'rhs_mag_an_m14_th3';
  player addItemToVest 'rhs_mag_an_m14_th3';
  player addItemToVest 'rhs_mag_an_m8hc';
  player addItemToVest 'rhs_mag_an_m8hc';
  player addItemToVest 'rhs_mag_an_m8hc';
  player addItemToVest 'rhs_mag_an_m8hc';
  player addItemToBackpack 'FirstAidKit';
  player addItemToBackpack 'FirstAidKit';
  player addItemToBackpack 'FirstAidKit';
  player addItemToBackpack 'FirstAidKit';
  player addItemToBackpack 'FirstAidKit';
  player addItemToBackpack 'HandGrenade';
  player addItemToBackpack 'HandGrenade';
  player addItemToBackpack 'rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red';
  player addItemToBackpack 'rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red';
  player addItemToBackpack 'rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red';
  player addItemToBackpack 'rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red';
  player addItemToBackpack 'rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red';
  player addItemToBackpack 'rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red';
  player addItemToBackpack 'rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red';
  player addItemToBackpack 'rhsusf_mag_17Rnd_9x19_FMJ';
  player addItemToBackpack 'rhsusf_mag_17Rnd_9x19_FMJ';
  player linkItem 'ItemMap';
  player linkItem 'ItemCompass';
  player linkItem 'ItemWatch';
  player linkItem 'ItemRadio';
  player linkItem 'ItemGPS';
  player linkItem 'NVGoggles_OPFOR';
  player linkItem 'Rangefinder';
};